server:
  port: 8095
spring:
  application:
    name: Notifications
  kafka:
    producer:
      bootstrap-servers: localhost:9092,localhost:9094,localhost:9096
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JacksonJsonSerializer
      properties:
        min.insync.replicas: 2
    consumer:
      bootstrap-servers: localhost:9092,localhost:9094,localhost:9096
      #key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      #value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: ru.slisarenko.entity_library.dto.*
        allow.auto.create.topics: true
      group-id: group-id-notification